version: '3.8'

services:
  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379:6379'
    restart: always

  app:
    build: .
    container_name: nestjs-app
    ports:
      - '4000:4000'
    environment:
      - PORT=3000
      - DB_PORT=5432
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=4444
      - DB_NAME=lesson
    depends_on:
      - redis
    restart: always
